### ISSUE TITLE
Micro test suite?

### ISSUE THREAD

**Issue by maxmechanic** [wham-js/web-audio-advent-calendar#2]
Would it be worth having a tiny set of assertions to make sure everything is interoperable (are there the expected start/connect fns, maybe an opinion on an audio node namespace, etc)? Maybe just something for folks to check against while on advent-ures.

**Comment by coleww** [comment]
_nice_ yeah nanogenmo is consuming most of my code brain time, but I can probably whip up a synth template in no time. 

yeah there should be start/stop/connect. and a fn that exposes any input nodes for FX things. constructor function that takes an audioContext and maybe some `{}` options. 

i think my web audio blog thing might be a good template unless there is something grossly wrong with it. But then again what Sole has been doing with the openMusic audioNode drop ins might also be a good template. IDK, i'm aiming more for like "high-level pre-built audio-graph" magic so ppl can get straight to the browser dubstep

as for namespace...i am thinking we should have a single tag for this on npm, but other than that i leave it unto people to name things as they please. 

And if people want to do something else, they can just copy the `test.js` and `npm install --save-dev tape`

**Comment by coleww** [comment]
https://github.com/wham-js/web-audio-synth-template :+1: needs a lil cleanup and work. I'm probably gonna copy paste a ton of commented-out boiler plate to make things a lil easier.
